#!/bin/sh

#     ███████╗██╗  ██╗██████╗  ██████╗ ██████╗ ████████╗███████╗
#     ██╔════╝╚██╗██╔╝██╔══██╗██╔═══██╗██╔══██╗╚══██╔══╝██╔════╝
#     █████╗   ╚███╔╝ ██████╔╝██║   ██║██████╔╝   ██║   ███████╗
#     ██╔══╝   ██╔██╗ ██╔═══╝ ██║   ██║██╔══██╗   ██║   ╚════██║
#  ██╗███████╗██╔╝ ██╗██║     ╚██████╔╝██║  ██║   ██║   ███████║
#  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝      ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚══════╝

export FILE="thunar"
export EDITOR="code"
export EDITOR2="vim"
export READER="zathura"
export TERMINAL="kitty"
export BROWSER="firefox"

export HISTCONTROL=erasedups:ignoreboth
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
export HISTIGNORE="&:clear:ls:cd:[bf]g:exit:[ t\]*"
export HISTORY_IGNORE="(ls|cd|pwd|exit|sudo reboot|history|cd -|cd ..)"

export MOZ_USE_OMTC=1
export TF_CPP_MIN_LOG_LEVEL=2
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT="MToolkit wmname LG3D"

export SUDO_PROMPT="[󱕴] Password [󱕴]: "
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

export PATH="$HOME/.local/bin:$HOME/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
export PATH="/usr/local/games:/usr/games:/usr/share/games:$PATH"
export PATH="/usr/local/sbin:/usr/sbin:/sbin:$PATH"
export PATH="/root/.local/bin:/snap/bin:/usr/sandbox:$PATH"
export PATH="$HOME/.local/share/flatpak/exports/share/applications:$HOME/.local/share/flatpak/exports/bin/:/var/lib/flatpak/exports/share/applications:$PATH"
export PATH="$HOME/.local/share/cargo/bin:$HOME/.cargo/bin:/usr/local/go/bin:$PATH"

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export ZSH="$HOME/.oh-my-zsh"
# export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
# export ZPLUGDIR="$ZDOTDIR/plugins"
# export GOPATH="$XDG_DATA_HOME/go"
# export CARGO_HOME="$XDG_DATA_HOME/cargo"
# export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
# export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
# export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
# export ICEAUTHORITY="$XDG_CACHE_HOME/ICEauthority"
