#!/bin/sh

#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║     
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║     
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝

## Autostart
$HOME/.config/bspwm/scripts/autostart.sh &

## Pywal Colors
. "${HOME}/.cache/wal/colors.sh"

## Workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

## Rules
bspc rule -a code focus=on
bspc rule -a kitty focus=on
bspc rule -a thunar focus=on
bspc rule -a firefox-esr focus=on
# bspc rule -a <Application> desktop='^1'
# bspc rule -a <Application> desktop='^2'
# bspc rule -a <Application> desktop='^3'
# bspc rule -a <Application> desktop='^4'
# bspc rule -a <Application> desktop='^5'
# bspc rule -a <Application> desktop='^6'
# bspc rule -a <Application> desktop='^7'
# bspc rule -a <Application> desktop='^8'
# bspc rule -a <Application> desktop='^9'
# bspc rule -a <Application> desktop='^10'

## Global Settings
bspc config single_monocle                  false
bspc config click_to_focus                  none
bspc config automatic_scheme                alternate
bspc config initial_polarity                second_child
bspc config paddingless_monocle             true
bspc config focus_follows_pointer           false

## Windows Settings
bspc config padding                         10
bspc config window_gap                      12
bspc config split_ratio                     0.52
bspc config gapless_monocle                 true
bspc config borderless_monocle              true

## Moving and Resize windows Settings
bspc config pointer_modifer                 mod4
bspc config pointer_action1                 move
bspc config pointer_action2                 resize_side
bspc config pointer_action3                 resize_corner

## Borders Settings
bspc config border_width                    3
bspc config border_radius                   15

## Colours Settings
bspc config presel_border_color             "$color1"
bspc config normal_border_color             "$color0"
bspc config active_border_color             "$color15"
bspc config focused_border_color            "$color15"

## Documentation
# Spanish -> https://github.com/Bleyom/bspwm-basics
# English -> https://dharmx.is-a.dev/bspwm-basics/
