#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#   █████╗ ██╗   ██╗████████╗ ██████╗ ███████╗████████╗ █████╗ ██████╗ ████████╗
#  ██╔══██╗██║   ██║╚══██╔══╝██╔═══██╗██╔════╝╚══██╔══╝██╔══██╗██╔══██╗╚══██╔══╝
#  ███████║██║   ██║   ██║   ██║   ██║███████╗   ██║   ███████║██████╔╝   ██║   
#  ██╔══██║██║   ██║   ██║   ██║   ██║╚════██║   ██║   ██╔══██║██╔══██╗   ██║   
#  ██║  ██║╚██████╔╝   ██║   ╚██████╔╝███████║   ██║   ██║  ██║██║  ██║   ██║   
#  ╚═╝  ╚═╝ ╚═════╝    ╚═╝    ╚═════╝ ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   
#                                                                               

# Configurar la distribucion del teclado a Español Latinoamericano
setxkbmap -layout latam &

# Reajustar las dimesiones de la pantalla
# xrandr --output Virtual1 --mode 1920x1080 --rate 75.00 &

# Reajustar fondo de pantalla
nitrogen --restore &

# Ejecutar compositor de ventanas
picom --config $HOME/.config/picom/picom.conf &

# Ejecutar barras de tareas
$HOME/.config/bspwm/scripts/polybar.sh &

# Reajustar paleta de colores de Pywal
$HOME/.config/bspwm/scripts/nitrogen.sh &

# Habilitar autenticador para rofi
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

# Bloquear cursor en zonas del polybar 
xsetroot -cursor_name left_ptr &

# Habilitar gestor de bateria de xfce
xfce4-power-manager &

# Colores
. "${HOME}/.cache/wal/colors.sh"


#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║     
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║     
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
#                                                               

bspc monitor -d I II III IV V VI VII VIII IX X

# bspc rule -a Gimp desktop='^8' state=floating 
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc config window_gap 15
bspc config split_ratio 2
bspc config border_width 2

bspc config focused_border_color "$color4"
bspc config active_border_color "$color15"
bspc config normal_border_color "$color6"

bspc config presel_border_color "$color1"
bspc config presel_feedback_color "$color2"

bspc config single_monocle false
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config paddingless_monocle true
bspc config focus_follows_pointer true

