include-file                = ~/.config/polybar/colors.ini
include-file                = ~/.config/polybar/modules.ini

[global/wm]
    margin-top              = 0
    margin-bottom           = 0

[configuracion-global]
    wm-restack              = bspwm
    fixed-center            = true
    monitor-strict          = false
    bottom                  = false
    height                  = 3%
    offset-y                = 1.2%
    background              = ${theme.background}
    foreground              = ${theme.foreground}
    border-color            = ${theme.background}
    border-size             = 0 
    module-margin-left      = 2
    module-margin-right     = 2
    radius-top              = 10
    radius-bottom           = 10
    font-0                  = "Iosevka Nerd Font:style=Bold:size=12;4"
    font-1                  = "Iosevka Nerd Font:style=Bold:size=14;4"
    font-2                  = "Iosevka Nerd Font:style=Bold:size=16;4"
    font-3                  = "Iosevka Nerd Font:style=Bold:size=20;4"

[module/power]
type = custom/text
content = "%{T1}  %{T-}"
click-left              = ~/.config/polybar/menu/powermenu.sh

[module/title]
    type                                = custom/script
    exec                                = echo "$USER"
    label                               = "  %{T2}%output%%{T-} "


; [bar/barra-logo]
;     inherit                 = configuracion-global
;     width                   = 3%
;     offset-x                = 1%
;     
;     modules-center          = distro-logo

[bar/barra-metricas]
    inherit                 = configuracion-global
    width                   = 30%
    offset-x                = 69%
    modules-center          = filesystem pulseaudio memory cpu packages htb-networks bluetooth

[bar/barra-escritorios]
    inherit                 = configuracion-global
    width                   = 30%
    font-0                  = "Iosevka Nerd Font:style=Bold:size=16;4"
    offset-x                = 1%
    modules-center          = power workspaces title
    module-margin-left      = 1
    module-margin-right     = 1

[bar/barra-aplicaciones]
    inherit                 = configuracion-global
    width                   = 20%
    offset-x                = 40%
    modules-center          = openweathermap date clock
    module-margin-left      = 2
    module-margin-right     = 2
; bluetooth htb-networks network 

[settings]
    throttle-output         = 5
    throttle-input-for      = 30
    throttle-output-for     = 10
    screenchange-reload     = false
    compositing-border      = over
    compositing-overline    = over
    compositing-underline   = over
    compositing-background  = source
    compositing-foreground  = over
    format-foreground       = 
    format-background       =
    format-underline        =
    format-overline         =
    format-spacing          =
    format-padding          =
    format-margin           =
    format-offset           =
    pseudo-transparency     = false


; [bar/fecha]
;     inherit                 = configuracion-global
;     width                   = 10%
;     offset-x                = 6.5%
;     click-left              = evolution
;     modules-center          = date 


; [bar/wifi]
;     inherit                 = configuracion-global
;     width                   = 5%
;     offset-x                = 17%
;     click-left              = ~/.config/polybar/menu/wifi.sh
;     click-right             = nm-connection-editor
;     modules-center          = network


; [bar/redes]
;     inherit                 = configuracion-global
;     width                   = 5% 
;     offset-x                = 22.5%
;     click-left              = ~/.config/polybar/menu/networks.sh
;     modules-center          = redes




; [bar/temperatura]
;     inherit                 = configuracion-global
;     width                   = 5%
;     offset-x                = 72%
;     click-right             = ~/.config/polybar/menu/weather_browser.sh
;     modules-center          = openweathermap


; [bar/bluetooth]
;     inherit                 = configuracion-global
;     width                   = 5%
;     font-0                  = "Iosevka Nerd Font:style=Bold:size=16;5"
;     offset-x                = 77.5%
;     click-left              = blueman-manager
;     modules-center          = bluetooth


; [bar/bateria]
;     inherit                 = configuracion-global
;     width                   = 5%
;     offset-x                = 83%
;     click-left              = xfce4-power-manager-settings
;     modules-center          = battery


; [bar/audio]
;     inherit                 = configuracion-global
;     width                   = 5%
;     offset-x                = 88.5%
;     click-right             = pavucontrol
;     modules-center          = pulseaudio
    

; [bar/brillo]
;     inherit                 = configuracion-global
;     width                   = 5%
;     offset-x                = 94%
;     modules-center          = backlight

